### ISSUE TITLE
Could you please provide the evaluation metrics code? Thank you.

### ISSUE THREAD

**Issue by hahalsp** [Arhosseini77/SUM#5]
Hello, Author,

I am very interested in your research and have implemented your code. The prediction results obtained from the trained model are excellent. However, I have a question and hope you can assist me. The predicted images generated by the model exhibit checkerboard-like artifacts, but the images in your paper do not show such issues. Could you please share what processing you applied to smooth the images? I may pursue research in this direction in the future, and I was wondering if you could provide the evaluation metrics code you used. Thank you.

**Comment by Arhosseini77** [comment]
Hello,

Thank you for your interest in our research and for taking the time to implement our code. I’m glad to hear that the prediction results from the trained model meet your expectations.

Regarding the checkerboard-like artifacts you mentioned, I want to clarify that the images presented in the paper are direct outputs from the model available on our GitHub repository. The pixelation or checkerboard effects that you observe upon zooming in are inherent to the model's output, as no additional post-processing is applied to the images.

For evaluation, we utilized metrics such as **KLD**, **SIM**, **NSS**, **AUC**, and **CC**. The implementation for these metrics can be found in the `utils/loss_function.py` file in the repository. Additionally, the code for evaluating the model across different datasets is available in the `validation.py` file. You may also find further details in our [paper](https://arxiv.org/abs/2406.17815).

If you have any further questions or need additional assistance, please don’t hesitate to reach out. I’d be happy to help!

**Comment by hahalsp** [comment]
Thank you.
